### ISSUE TITLE
No items given on QS-Inventory 

### ISSUE THREAD

**Issue by NatasWillDoIt** [Pluto-Really/fp-startergift#3]
when i use the item Starter_Gift it triggers all event other then the give item

**Comment by NatasWillDoIt** [comment]
also i get not errors on server side or client

**Comment by Andyauk** [comment]
> when i use the item Starter_Gift it triggers all event other then the give item

yes no items, no errors.

**Comment by Pluto-Really** [comment]
Please download a new copy. This Issue has been fixed.

**Comment by Andyauk** [comment]
> Please download a new copy. This Issue has been fixed.

Thanks will try when I get home, keep up the great work
